[project]
name = ""
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
dependencies = [
	"Flask>=2.0",
	"requests>=2.28",
	"python-dotenv>=1.0",
	"PyJWT>=2.8",
	"uvicorn>=0.22",
]
